apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-appkube-editor-task
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this Workspace.
  params:
    - name: workingDir
      description: Working directory parameter
      default: ""
  steps:
    - name: read-directory
      image: synectiks/appkube-editor-base:latest
      script: echo $(params.workingDir) && ls -al $(params.workingDir)
    - name: appkube-editor-build
      image: synectiks/appkube-editor-base:latest
      securityContext:
        runAsUser: 0
      workingDir: $(params.workingDir)
      script: |
        #!/bin/bash 
        echo building service from container
        
        # Go to cloned directory
        cd /workspace/source/

        # Install wire - this is moved to base container
        # go install github.com/google/wire/cmd/wire@latest

        # Generate wire files
        $(go env GOPATH)/bin/wire gen -tags oss ./pkg/server/ ./pkg/cmd/grafana-cli/runner

        # Install yarn and run yarn install - this is moved to base container
        RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash \
        && /bin/bash -c "source /root/.nvm/nvm.sh && nvm install v16.17.0" \
        && /bin/bash -c "source /root/.nvm/nvm.sh && yarn install --immutable"

        ENV NVM_DIR "/root/.nvm"
        # Load nvm and bash completion
        RUN /bin/bash -c "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\" && [ -s \"$NVM_DIR/bash_completion\" ] && . \"$NVM_DIR/bash_completion\""

        cd conf
        sed -i 's/host = 127\.0\.0\.1:5432/host = postgresql.ch8wfucynpvq.us-east-1.rds.amazonaws.com:5431/' defaults.ini
        sed -i 's/password = postgres/password = Synect!ks2023/' defaults.ini

        # Go to appkube-editor root directory
        cd ../

        # Compile backend (go server)
        go run build.go setup && go run build.go build

        # Build UI
        source /root/.nvm/nvm.sh
        yarn build

        chmod -R +x data