apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: {{ include "appkube-editor.fullname" . }}
  labels:
    {{- include "appkube-editor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appkube-editor.selectorLabels" . | nindent 4 }}
