{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Values.virtualservice.namespace }}
spec:
  hosts:
  - {{ .Values.virtualservice.hosts }}
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
{{- range .Values.virtualservice.httpRules }}
  - match:
    - uri:
        prefix: {{ .prefix }}
    rewrite:
      uri: {{ .rewrite }}
    route:
    - destination:
        host: {{ .destination.host }}
        port:
          number: {{ .destination.port }}
{{- end }}
{{- end }}
